"use client";
import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import { usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import Hydration from "@/context/hydation";

const nunito = Nunito_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          nunito.className
        )}>
        <Hydration />

        {path !== "/login" && <Navbar />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
